import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
   variable: "--font-onest",
   subsets: ["latin"],
   weight: ["500", "600", "700"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body
            className={`${onest.className} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
